#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build Optional Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_MFE: true
      ENABLE_BACKUP: false
      ENABLE_CREDENTIALS: false
      ENABLE_LICENSE_MANAGER: false

      # environment settings
      # --------------------------------------------
      SUBDOMAIN: {{ cookiecutter.environment_subdomain }}
      DOMAIN_NAME: {{ cookiecutter.global_root_domain }}
      SITE_NAME: {{ cookiecutter.global_platform_name }}
      AWS_REGION: {{ cookiecutter.global_aws_region }}
      ENVIRONMENT_ID: {{ cookiecutter.environment_name }}
      NAMESPACE: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}
      EKS_CLUSTER_NAME: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.global_platform_shared_resource_identifier }}
      S3_BUCKET_PREFIX: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}

    steps:
      - uses: actions/checkout@{{ cookiecutter.ci_actions_checkout_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@{{ cookiecutter.ci_actions_setup_build_action_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@{{ cookiecutter.ci_actions_configure_aws_credentials_version }}
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@{{ cookiecutter.ci_openedx_actions_tutor_k8s_init_version }}
        with:
          eks-namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          eks-cluster-name: {% raw %}${{ env.EKS_CLUSTER_NAME }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}
          tutor-version: "{{ cookiecutter.ci_build_tutor_version }}"
          tutor-mfe-version: "{{ cookiecutter.ci_build_tutor_mfe_version }}"
          kubectl-version: "{{ cookiecutter.ci_build_kubectl_version }}"

      - name: Build MFE
        if: {% raw %}${{ env.ENABLE_MFE == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-mfe@v0.1.6

      - name: Build Backup
        if: {% raw %}${{ env.ENABLE_BACKUP == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-backup@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_backup_version }}

      - name: Build Credentials
        if: {% raw %}${{ env.ENABLE_CREDENTIALS == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-credentials@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_credentials_version }}
        with:
          version: {{ cookiecutter.ci_deploy_tutor_plugin_credentials_version }}
          aws-ecr-repo: openedx_credentials

      - name: Build License Manager
        if: {% raw %}${{ env.ENABLE_LICENSE_MANAGER == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-license-manager@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_license_manager_version }}
