#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build openedx container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: {{ cookiecutter.global_aws_region }}

      CUSTOM_THEME_REPOSITORY: {{ cookiecutter.ci_build_theme_repository }}
      CUSTOM_THEME_REPOSITORY_ORGANIZATION: {{ cookiecutter.ci_build_theme_repository_organization }}
      CUSTOM_THEME_REPOSITORY_REF: {{ cookiecutter.ci_build_theme_ref }}

    steps:
      - uses: actions/checkout@{{ cookiecutter.ci_actions_checkout_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@{{ cookiecutter.ci_actions_configure_aws_credentials_version }}
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      #------------------------------------------------------------------------
      # install and configure tutor
      #------------------------------------------------------------------------
      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@{{ cookiecutter.ci_openedx_actions_tutor_k8s_init_version }}

      #------------------------------------------------------------------------
      # Add any Python requirements here.
      # These include:
      # - generic Python PyPi packages
      # - Xblocks
      # - Open edX Plugin(s)
      # - your own custom repos
      #
      # note that `repository-token` is optional and is only needed for
      # private repositories
      #------------------------------------------------------------------------
      - name: Add an edx plugin
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v0.0.5
        with:
          repository: openedx-plugin-example
          repository-organization: lpm0073
          repository-ref: main

      - name: Add an Xblock
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@v0.0.5
        with:
          repository: edx-ora2
          repository-organization: openedx
          repository-ref: master


      #------------------------------------------------------------------------
      # Build and upload the Docker container
      #------------------------------------------------------------------------
      - name: Build openedx
        uses: openedx-actions/tutor-plugin-build-openedx@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_openedx_version }}
        with:
          custom-theme-repository: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY }}{% endraw %}
          custom-theme-repository: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY_ORGANIZATION }}{% endraw %}
          custom-theme-repository-ref: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY_REF }}{% endraw %}
