#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build Optional Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_BACKUP: true
      ENABLE_CREDENTIALS: false
      ENABLE_MFE: true

      SUBDOMAIN: {{ cookiecutter.environment_subdomain }}
      DOMAIN_NAME: {{ cookiecutter.global_root_domain }}
      SITE_NAME: {{ cookiecutter.global_platform_name }}
      AWS_REGION: {{ cookiecutter.global_aws_region }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@v0.0.6

      - name: Build Backup
        if: {% raw %}${{ env.ENABLE_BACKUP == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-backup@v0.1.7

      - name: Build Credentials
        if: {% raw %}${{ env.ENABLE_CREDENTIALS == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-credentials@v0.1.5

      - name: Build MFE
        if: {% raw %}${{ env.ENABLE_MFE == 'true' }}{% endraw %}
        uses: openedx-actions/tutor-plugin-build-mfe@v0.1.5
        with:
          subdomain: ${SUBDOMAIN}
          domain-name: ${DOMAIN_NAME}
          site-name: ${SITE_NAME}
