#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUBDOMAIN: {{ cookiecutter.environment_subdomain }}
      DOMAIN_NAME: {{ cookiecutter.global_root_domain }}
      SITE_NAME: {{ cookiecutter.global_platform_name }}
      AWS_REGION: {{ cookiecutter.global_aws_region }}

      CUSTOM_THEME_REPOSITORY: {{ cookiecutter.ci_build_theme_repository }}
      CUSTOM_THEME_REPOSITORY_REF: {{ cookiecutter.ci_build_theme_ref }}

      CUSTOM_PLUGIN_REPOSITORY: {{ cookiecutter.ci_build_plugin_repository }}
      CUSTOM_PLUGIN_REPOSITORY_ORGANIZATION: {{ cookiecutter.ci_build_plugin_org }}
      CUSTOM_PLUGIN_REPOSITORY_REF: {{ cookiecutter.ci_build_plugin_ref }}

      CUSTOM_XBLOCK_REPOSITORY: {{ cookiecutter.ci_build_xblock_repository }}
      CUSTOM_XBLOCK_REPOSITORY_ORGANIZATION: {{ cookiecutter.ci_build_xblock_org }}
      CUSTOM_XBLOCK_REPOSITORY_REF: {{ cookiecutter.ci_build_xblock_ref }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      - name: Build openedx
        uses: openedx-actions/tutor-plugin-build-openedx@v0.1.9
        with:
          custom-theme-repository: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY }}{% endraw %}
          custom-theme-repository-ref: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY_REF }}{% endraw %}

          custom-plugin-repository: {% raw %}${{ env.CUSTOM_PLUGIN_REPOSITORY }}{% endraw %}
          custom-plugin-repository-organization: {% raw %}${{ env.CUSTOM_PLUGIN_REPOSITORY_ORGANIZATION }}{% endraw %}
          custom-plugin-repository-ref: {% raw %}${{ env.CUSTOM_PLUGIN_REPOSITORY_REF }}{% endraw %}

          custom-xblock-repository: {% raw %}${{ env.CUSTOM_XBLOCK_REPOSITORY }}{% endraw %}
          custom-xblock-repository-organization: {% raw %}${{ env.CUSTOM_XBLOCK_REPOSITORY_ORGANIZATION }}{% endraw %}
          custom-xblock-repository-ref: {% raw %}${{ env.CUSTOM_XBLOCK_REPOSITORY_REF }}{% endraw %}
