#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: May-2022
#
# usage: Creates a Tutor Docker image for MFE using the latest stable version of
#        the repo. Registers the new container in AWS ECR.
#------------------------------------------------------------------------------
name: Prod Build MFE Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: mfe
      ECR_REGISTRY: {{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com
      TUTOR_VERSION: v13.1.5
    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{ cookiecutter.global_aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install Tutor (from source)
        run: |-
          pip install --upgrade pyyaml
          echo "TUTOR_ROOT=$GITHUB_WORKSPACE/tutor" >> $GITHUB_ENV
          git clone https://github.com/overhangio/tutor.git
          cd tutor
          git checkout ${TUTOR_VERSION}
          pip install -e .
          echo "TUTOR_VERSION=$(tutor --version | cut -f3 -d' ')" >> $GITHUB_ENV

      - name: Set Tutor Root in the Workspace
        run: |
          echo "REPOSITORY_TAG=$TUTOR_VERSION-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TUTOR_ROOT=$GITHUB_WORKSPACE/tutor" >> $GITHUB_ENV

      - name: Install Tutor MFE plugin
        run: |-
          pip install git+https://github.com/overhangio/tutor-mfe.git
          tutor plugins enable mfe
          tutor config save

      - name: Test Tutor and Environment
        run: |
          tutor --version
          echo "REPOSITORY_TAG=$REPOSITORY_TAG"
          echo "TUTOR_ROOT=$TUTOR_ROOT"

      - name: Render Tutor Config
        run: |
          tutor config save --set MFE_DOCKER_IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:${REPOSITORY_TAG}

      - name: Build the image
        run: tutor images build mfe

      - name: Push the image
        run: |
          tutor images push mfe
          docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${REPOSITORY_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

      - name: Docker image:tag
        run: |
          echo "Docker image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${REPOSITORY_TAG}"
