#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}
spec:
  acme:
    email: no-reply@{{ cookiecutter.global_root_domain }}
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          # NOTE: make sure that this is the hosted Zone ID for
          # for the environment domain.
          route53:
            region: {{ cookiecutter.global_aws_region }}
            hostedZoneID: {{ cookiecutter.global_aws_route53_hosted_zone_id }}
