apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-nginx-lms
  namespace: openedx
data:
  configmap_site_lms: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <title>From config map</title>
      </head>
      <body>

        <h1>Loaded from config map!</h1>

      </body>
    </html>
