apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-nginx-cms
  namespace: openedx
data:
  configmap_cms_conf: |
    upstream cms-backend {
      server cms:8000 fail_timeout=0;
    }

    server {
      listen 80;
      server_name studio.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }};

      access_log /var/log/nginx/access.log;
      client_max_body_size 250M;
      server_tokens off;

      rewrite ^(.*)/favicon.ico$ /static/images/favicon.ico last;

      location @proxy_to_cms_app {
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_pass http://cms-backend;
      }

      location / {
        try_files $uri @proxy_to_cms_app;
      }
    }
